version: "3.5"

services:
  postgres-mmark:
    container_name: postgres-mmark
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - ./.docker-volumes/postgres:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      mmark-net:
        ipv4_address: 172.28.1.1

  liquibase-mmark:
    container_name: liquibase-mmark
    image: liquibase/liquibase:${LIQUIBASE_VERSION}
    restart: on-failure
    command: --defaultsFile=liquibase.properties update
    depends_on:
      - postgres-mmark
    volumes:
      - ./db/:/liquibase/changelog/
      - ./db/:/liquibase/classpath/
      - ./db/liquibase.properties:/liquibase/liquibase.properties
    networks:
      mmark-net:
        ipv4_address: 172.28.1.2

  grafana-mmark:
    container_name: grafana-mmark
    image: grafana/grafana:${GRAFANA_VERSION}
    restart: on-failure
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana:/etc/grafana/provisioning
      - ./.docker-volumes/grafana:/var/lib/grafana
    ports:
      - ${GRAFANA_PORT}:3000
    networks:
      mmark-net:
        ipv4_address: 172.28.1.3

  prometheus-mmark:
    container_name: prometheus-mmark
    image: prom/prometheus:${PROMETHEUS_VERSION}
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./.docker-volumes/prometheus:/prometheus
    ports:
      - ${PROMETHEUS_PORT}:9090
    networks:
      mmark-net:
        ipv4_address: 172.28.1.4

  mmark-app:
    container_name: mmark-app
    build: ./
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${APP_PORT}:9000
    depends_on:
      - postgres-mmark
    networks:
      mmark-net:
        ipv4_address: 172.28.1.5

networks:
  mmark-net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16