server:
  port: 9000

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

cache:
  user-maximum-size: 100000
  user-expired-time-hours: 4

postgres:
  url: ${POSTGRES_URL}
  host: ${POSTGRES_HOST}
  port: ${POSTGRES_PORT}
  db: ${POSTGRES_DB}
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  max-active-connections: 25
  max-pending-queries: 100000
  max-connection-ttl: 120000
  max-idle-time: 300000

app:
  url: ${APP_URL:9000}
  api-path: ${API_PATH:/}
  hash-salt: ${HASH_SALT}
  jwt-signing-key: ${JWT_SIGNING_KEY}
  token-ttl: ${TOKEN_TTL:4}