server:
  port: 9000

cache:
  user-maximum-size: 100000
  user-expired-time-hours: 4

postgres:
  url: ${POSTGRES_URL}
  host: ${POSTGRES_HOST}
  port: ${POSTGRES_PORT}
  db: ${POSTGRES_DB}
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  max-active-connections: 25
  max-pending-queries: 100000
  max-connection-ttl: 120000
  max-idle-time: 300

app:
  url: ${APP_URL}
  api-path: ${API_PATH:/}
  jwt-signing-key: ${JWT_SIGNING_KEY}
  token-ttl: ${TOKEN_TTL:4}